name: Automatic Encryption Decryption
on:
  schedule:
    # Everyday At 12:05 AM 
    - cron: "5 0 * * *"
  workflow_dispatch:
jobs:
  build_data:
    runs-on: windows-latest
    env: 
      REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
      username: github-actions
      SEC_PASS: ${{ secrets.SEC_PASS }}
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e "install.packages('gpg', dependencies= TRUE)"
      - name: Fetch data
        run: |
          Rscript testmain.R   
      - name: Update encrypted file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
